package com.dreamlabs.selenium;
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
public class JsfundTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void jsfund() {
    // Test name: jsfund
    // Step # | name | target | value
    // 1 | open | /passport | 
    driver.get("https://e.jsfund.cn/passport");
    // 2 | setWindowSize | 550x692 | 
    driver.manage().window().setSize(new Dimension(550, 692));
    // 3 | click | id=loginno | 
    driver.findElement(By.id("loginno")).click();
    // 4 | type | id=loginno | 420303198209121736
    driver.findElement(By.id("loginno")).sendKeys("420303198209121736");
    // 5 | type | id=pwd | 828100
    driver.findElement(By.id("pwd")).sendKeys("828100");
    // 6 | click | id=submit_btn | 
    driver.findElement(By.id("submit_btn")).click();
    // 7 | click | id=accodealquery | 
    driver.findElement(By.id("accodealquery")).click();
    // 8 | click | id=hist2 | 
    driver.findElement(By.id("hist2")).click();
    // 9 | click | name=input | 
    driver.findElement(By.name("input")).click();
    // 10 | click | id=servicebill | 
    driver.findElement(By.id("servicebill")).click();
    // 11 | click | id=2020年06月 | 
    driver.findElement(By.id("2020年06月")).click();
    // 12 | click | id=myproperty | 
    driver.findElement(By.id("myproperty")).click();
    // 13 | runScript | window.scrollTo(0,4) | 
    js.executeScript("window.scrollTo(0,4)");
  }
}
